### ISSUE TITLE
Address the inventory.py patch

### ISSUE THREAD

**Issue by mbruzek** [redhat-performance/scale-ci-ansible#153]
The patch to `inventory.py` was put in #46 to support faster scaleup times because the dynamic inventory use the openstack cli to generate the list of nodes. The time it would take to get all app-nodes when we scaled to larger numbers (2000) was significant, so we changed the Python code to optionally not list the app-nodes when an environment variable is set (and we only use that for scaleup operations).

The upstream `inventory.py` is changing and keeping this patch is more difficult. We should take some time to determine a better more permanent solution for this.

Options include:
* Generate a [static inventory](https://github.com/openshift/openshift-ansible/blob/master/playbooks/openstack/configuration.md#using-a-static-inventory) once before the scaleup operation and use that static file for the remaining scale operations. I think this would work because the new_nodes are provided in a different static inventory file.
* Make a PR to openshift-ansible for that changes the inventory to skip the app-nodes, similar to how the patch works now. This would help when we get large numbers of app-nodes such as 2000+.
* Are there any other options/ideas?

**Comment by akrzos** [comment]
There is no more inventory.py patch. Closing.
