### ISSUE TITLE
AnsibleUndefinedVariable: 'openshift_loadbalancer_frontends' is undefined

### ISSUE THREAD

**Issue by mbruzek** [redhat-performance/scale-ci-ansible#176]
Performing an install with 3.11 and openshift-ansible master branch I ran into a new error.

```
TASK [openshift_loadbalancer : Configure haproxy] ******************************

fatal: [lb-0.scale-ci.example.com]: FAILED! => {
    "changed": false, 
    "msg": "AnsibleUndefinedVariable: 'openshift_loadbalancer_frontends' is undefined"
}
```

**Comment by jeremyeder** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1613981

**Comment by mbruzek** [comment]
Thanks @jeremyeder I found that it was changed and in the process of being reverted by: https://github.com/openshift/openshift-ansible/pull/9499

**Comment by jeremyeder** [comment]
Ack, thanks.  For my own understanding, why is an issue filed in this repo?

**Comment by akrzos** [comment]
Closing this issue since it seems stale.
