### ISSUE TITLE
Create the target-server with openshift installed via RPM

### ISSUE THREAD

**Issue by mbruzek** [redhat-performance/scale-ci-ansible#28]
The target-server (ansible-host) currently has openshift installed via pip. There are some commands such as `openshift server add floating ip <uuid> <address>` that do not work from the target-server, but do work from the openstack-server. Install the same packages that the undercloud server uses and see if that fixes the problem.

**Comment by akrzos** [comment]
Closing since this issue is stale and greater than a year old.
